#!/usr/bin/env python3
"""Assemble the generated sections into SUPPLEMENT_v1.md in paper order."""
import os, datetime
from pathlib import Path
HERE = Path(os.path.dirname(os.path.abspath(__file__)))

def grab(fn, start=None, end=None):
    t = (HERE/fn).read_text(encoding="utf-8")
    if start:
        i = t.index(start); t = t[i:]
    if end:
        j = t.find(end)
        if j > 0: t = t[:j]
    return t.rstrip()

TODO = "> **[NEEDS AUTHOR INPUT]**"
P=[]; w=P.append

w("# Supplementary Materials\n")
w("### Interpretive Governance of AI Reading Companions: A Curator-Governed "
  "Deployment Across Ten Canonical Texts\n")
w(f"*Supplement v2 — generated {datetime.date.today().isoformat()}. "
  "Every table in this document is produced by a script listed in S8.2 and "
  "regenerates offline from the archived data. Figures are generated by "
  "`make_figures.py` at 300 dpi in PNG and LZW-compressed TIFF.*\n")
w("---\n")
w("## Contents\n")
for line in [
 "- **S1** Worked example: *Nathan the Wise*, end to end",
 "- **S2** The drift instrument — lexicon, suffix patterns, A3 instruction, marker counts",
 "- **S3** System and controls — pipeline, the ten controls, schema, retrieval, dimension mapping",
 "- **S4** Corpus",
 "- **S5** Protocol",
 "- **S6** Governance log — scope, coding, usage, acceptance, timing, data integrity, provenance of the Cond_B follow-on question",
 "- **S7** Full results — per-book, per-cluster, all pairwise tests, book-level robustness, effect-size reconciliation, thread accumulation and response length, dimension decomposition",
 "- **S8** Open materials manifest"]: w(line)
w("")
w("**Items still requiring author input**, flagged inline with "
  "`[NEEDS AUTHOR INPUT]`:\n")
w("| Item | Where | Note |")
w("|---|---|---|")
for a,b_,c_ in [
 ("A populated A/B preview capture","S3.3",
  "the one interface step still unevidenced; 21 of the 46 proposals carry a stored preview. "
  "Four of the eight screenshots are also of a non-corpus book"),
 ("Repository update","S8.1",
  "the ablation condition, the four-way analysis and the supplement scripts are not yet in the public repository"),
 ("Archival deposit of code and data","S8.3",
  "the supplied Zenodo DOI is the predecessor *preprint*, not a materials deposit")]:
    w(f"| {a} | {b_} | {c_} |")
w("")
w("Resolved since v1: the pipeline diagram is now Figure S6; the repository "
  "URL and licence are recorded in S8.1; eight interface screenshots are "
  "catalogued in S3.3, four of them of the S1 worked-example text; the 3A "
  "dialogue and the governance History view are both evidenced; and the "
  "provenance of the Cond_B trailing question is established in S6.7.\n")
w("**Corrections to the earlier papers established here**, each with the "
  "evidence attached rather than asserted:\n")
w("| # | Correction | Where | Effect on conclusions |")
w("|---|---|---|---|")
for r in [
 ("1","Lexicon marker count: D1 = 18 (46 entries / 45 unique), not D1 = 16 (43 unique). "
      "The April 2026 narrowing of bare `emotional` to three phrases was applied in code "
      "but omitted from Appendix A.","S2.1.2","None — re-run under either list preserves "
      "every sign and significance verdict (S2.1.3)"),
 ("2","Published effect sizes are clipped: *r* is capped at 0.499 by a 1e-9 floor on p, and "
      "reported as 0.000 whenever the effect ran against the one-sided hypothesis.",
      "S7.5","Headline A2→B *r* = 0.496 reproduces exactly; the model effect is larger than "
      "published and the adverse D4 effect was being zeroed"),
 ("3","Two `hard_boundary` packets logged against *Confessions* contain *Art of War* content. "
      "Both marked applied; neither reached the live configuration.","S6.6",
      "Effective applications 24, not 26; Cond_B responses unaffected"),
 ("4","The governance log covers 59 proposals across 12 books; 46 across the ten corpus texts "
      "after excluding two non-corpus books.","S6.1","None — clarifies the denominator"),
 ("5","Two `author_display` strings are corrupted in the registry (`John Stuart Miller`, "
      "`Saint of Hippo Augustine`).","S4","None — canonical forms were sent to the models"),
 ("6","**The Cond_B trailing question is a governed behaviour, not an ungoverned platform "
      "artefact.** Two applied governance actions enable and specify it. Earlier drafts "
      "described it as the product surface undoing the governance layer.","S6.7",
      "**D1–D3 headline unaffected** (2 of 108 markers). §3.4's framing is replaced: "
      "governance proved reliable for semantic specification (99% book-anchored) and "
      "unreliable for lexical prohibition (89% used a forbidden phrase)"),
 ("7","Suffix incidence is 150/150, not 145/150; the seven regexes match 145. The "
      "\"stripped\" basis retains 5 follow-on questions.","S6.7, S2.2",
      "None — the residue is conservative for the governance claim")]:
    w("| " + " | ".join(r) + " |")
w("")
w("---\n")

w(grab("s1_worked_example.md")); w("\n---\n")
w("## S2 — The drift instrument\n")
_lex = grab("s2_1_lexicon.md").replace("## S2.1 —", "### S2.1 —", 1).replace("## S2.2 —", "### S2.2 —", 1)
w(_lex); w("")
w("### S2.3 — Worked counting example\n")
w("A full annotation of one response under all four conditions — every "
  "lexicon match, the dimension it counts toward, and whether it fell inside "
  "the stripped suffix — is given in **S1.3**, with the surrounding responses "
  "reproduced in S1.2 so the matches can be checked against their context. It "
  "is placed there rather than duplicated here because the same example also "
  "carries the pack and the condition contrast.\n")
w(grab("s3_s6_s8.md", start="### S2.4", end="## S3 —")); w("")
w(grab("s2_5_marker_counts.md").replace("## S2.5", "### S2.5", 1)); w("\n---\n")
w(grab("s3_s6_s8.md", start="## S3 —", end="## S6 —")); w("\n---\n")
w(grab("supplement_tables.md", start="## S4 —", end="## S5 —")); w("\n---\n")
w(grab("supplement_tables.md", start="## S5 —", end="## S7.1")); w("\n---\n")

# S6: intro sections, then the 46-row log, then the rest
s6 = grab("s3_s6_s8.md", start="## S6 —", end="## S8 —")
cut = s6.index("### S6.3")
w(s6[:cut].rstrip()); w("")
w("### S6.2 — The complete log\n")
w(grab("governance_log_46.md", start="Raw export:").split("\n\n",1)[0] + "\n")
w(grab("governance_log_46.md", start="| # | Book"))
w("")
w("Full machine-readable version with proposal IDs, full from/to values and "
  "the complete curator transcript for each proposal: "
  "`governance_log_46.csv` (S8.1).\n")
w(s6[cut:].rstrip()); w("")
w(grab("s6_7_suffix_provenance.md")); w("\n---\n")

w("## S7 — Full results\n")
w(grab("supplement_tables.md", start="## S7.1").replace("\n## S7", "\n### S7")
  .replace("## S7.1", "### S7.1", 1)); w("")
w(grab("s7_6_7_thread_retrieval.md")); w("\n---\n")
w(grab("s3_s6_s8.md", start="## S8 —"))
w("")
w("---\n")
w("*End of supplement.*")

out = HERE.parent/"08_continuation_paper"/"SUPPLEMENT_v2.md"
out.write_text("\n".join(P), encoding="utf-8")
txt = out.read_text()
print("WROTE", out.name)
print("chars", f"{len(txt):,}", "| lines", f"{txt.count(chr(10)):,}",
      "| tables", txt.count("\n|---"), "| TODOs", txt.count("[NEEDS AUTHOR INPUT]"))
import re
print("\nHeadings:")
for m in re.finditer(r"^(#{2,3}) (.+)$", txt, re.M):
    print(("  " if len(m.group(1))==2 else "      ") + m.group(2)[:78])
