
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from _paths import DATA, CANON, EXPORT, HERE, data_file, canon_pack
#!/usr/bin/env python3
"""
Supplement tables S2.5, S4, S5, S7.1-S7.4 for the continuation paper.

STATISTICAL CONVENTIONS — reproduced exactly from drift_reduction_3way.py,
the script that produced the published figures:
  * Rates are per 1,000 tokens, computed PER RESPONSE, then averaged
    (mean-of-rates, not ratio-of-sums). Reproduces A2=8.921 / B=4.951 etc.
  * Paired Wilcoxon signed-rank, pairing by (book, question).
  * Published papers used a ONE-SIDED alternative for the directional
    governance contrasts and TWO-SIDED for the model effect (A1 vs A2).
    This supplement reports BOTH so a reader can check either.
  * Effect size r = Z / sqrt(N) with N = 150 (all pairs, not just non-zero),
    Z recovered from the TWO-SIDED p. Reproduces the published r = 0.496.

Input : 07_ablation_analysis/per_response_4way.csv (600 rows = 4 x 150)
        book_registry.json, protocol_15q.json
Output: supplement_tables.md, s7_per_book.csv, s7_pairwise.csv
Writes only into 09_supplement/; nothing is overwritten elsewhere.
"""
import csv, json, os, itertools
from collections import defaultdict
from scipy.stats import wilcoxon, norm
import statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)
GFI  = str(DATA)

rows = list(csv.DictReader(open(data_file("per_response_4way.csv"))))
for r in rows:
    for k in ("d1","d2","d3","d4","tokens"): r[k] = int(r[k])
    for k in ("d123_per1k","total_per1k","d123_per1k_raw","total_per1k_raw"): r[k] = float(r[k])
    r["stripped"] = r["stripped"] == "True"

reg   = json.load(open(os.path.join(GFI, "book_registry.json")))
BOOKS, CLUSTERS = reg["books"], reg["_clusters"]
proto = json.load(open(os.path.join(GFI, "protocol_15q.json")))

CONDS = ["A1","A2","A3","B"]
idx = defaultdict(dict)
for r in rows: idx[(r["ab"], r["qid"])][r["cond"]] = r
pairs = sorted(idx)
assert len(pairs) == 150 and all(len(idx[p]) == 4 for p in pairs)
NPAIRS = 150

def wtest(a, b, field):
    """Published convention. Returns one- and two-sided p, and r = Z/sqrt(150)."""
    xs = [idx[p][a][field] for p in pairs]
    ys = [idx[p][b][field] for p in pairs]
    d  = [x - y for x, y in zip(xs, ys)]
    nz = sum(v != 0 for v in d)
    ma, mb = st.mean(xs), st.mean(ys)
    base = dict(mean_a=ma, mean_b=mb, n=NPAIRS, n_nonzero=nz,
                pct=((mb - ma) / ma * 100 if ma else 0.0))
    if nz == 0:
        return dict(base, W=float("nan"), p1=1.0, p2=1.0, r=0.0)
    # 'greater' = a > b, i.e. the directional "ungoverned > governed" test
    W, p1 = wilcoxon(xs, ys, alternative="greater", zero_method="wilcox")
    _, p2 = wilcoxon(xs, ys, alternative="two-sided", zero_method="wilcox")
    z = abs(norm.ppf(p2 / 2)) if 0 < p2 < 1 else 0.0
    return dict(base, W=W, p1=p1, p2=p2, r=z / (NPAIRS ** 0.5))

def rate(sub, cats=("d1","d2","d3"), raw=False):
    """Mean-of-rates over a subset of responses, published convention."""
    f = {("d1","d2","d3"): "d123_per1k_raw" if raw else "d123_per1k",
         ("d1","d2","d3","d4"): "total_per1k_raw" if raw else "total_per1k"}[cats]
    return st.mean(r[f] for r in sub)

out = []; w = out.append

# S2.5 is generated by s2_5_marker_counts.py (it needs raw marker counts,
# which per_response_4way.csv does not store). Not duplicated here.

# ------------------------------------------------------------------ S4
w("## S4 — Corpus\n")
w("Ten public-domain texts in three genre clusters. `Companion` is the "
  "reader-facing persona configured on the platform.\n")
w("| # | Abbr | Title | Author | Cluster | Companion | Responses |")
w("|---|---|---|---|---|---|---|")
for n,(ab,b) in enumerate(sorted(BOOKS.items(), key=lambda kv:(kv[1]["cluster"], kv[1]["title"])),1):
    cnt = len([r for r in rows if r["ab"] == ab and r["cond"] == "B"])
    w(f"| {n} | `{ab}` | {b['title']} | {b['author_canonical']} | {b['cluster']} | "
      f"{b['companion']} | {cnt} × 4 |")
w("")
for k,v in CLUSTERS.items():
    ms = sorted(b["title"] for b in BOOKS.values() if b["cluster"] == k)
    w(f"- **{k} — {v}** ({len(ms)}): {', '.join(ms)}")
w("")
w("All ten texts are in the public domain and all ten authors are deceased; "
  "the governance configurations were authored by a curator, not by the authors. "
  "Two platform `author_display` strings are corrupted in the registry "
  "(`John Stuart Miller` for Mill; `Saint of Hippo Augustine` for Augustine). "
  "The canonical forms above were the ones supplied to the models; the display "
  "defect affects only the reader-facing label and is reported here for "
  "completeness.\n")

# ------------------------------------------------------------------ S5
w("## S5 — The 15-question protocol\n")
w("Every book receives the same 15 questions, phrased book-independently. "
  "`Primary drift` is the dimension each question was designed to elicit — a "
  "design annotation only, not used in scoring.\n")
w("| Q | Block | Primary drift | Question |")
w("|---|---|---|---|")
qs = proto["questions"]
for qid in sorted(qs):
    q = qs[qid]
    w(f"| {qid} | {q['block']} | {q['primary_drift']} | {q['text']} |")
w("")
w("**Blocks** — " + "; ".join(f"{k}: {v}" for k,v in proto["_blocks"].items()) + ".\n")
w("**Drift categories** — " + "; ".join(f"{k}: {v}" for k,v in proto["_drift_categories"].items()) + ".\n")
w(f"Total: {len(qs)} questions × 10 books × 4 conditions = **{len(qs)*10*4} responses**.\n")

# ------------------------------------------------------------------ S7.1
w("## S7.1 — Per-book D1–D3 rate by condition (per 1,000 tokens)\n")
w("Mean of per-response rates within each book (n = 15 per cell). "
  "Cond_B on the stripped basis.\n")
w("| Book | Cluster | A1 | A2 | A3 | B | Δ A2→B | Δ A3→B |")
w("|---|---|---|---|---|---|---|---|")
perbook = []
for ab,b in sorted(BOOKS.items(), key=lambda kv: kv[1]["title"]):
    m = {c: rate([r for r in rows if r["ab"] == ab and r["cond"] == c]) for c in CONDS}
    d2b = (m["B"]-m["A2"])/m["A2"]*100; d3b = (m["B"]-m["A3"])/m["A3"]*100
    perbook.append(dict(ab=ab, title=b["title"], cluster=b["cluster"], **m, d_a2b=d2b, d_a3b=d3b))
    w(f"| {b['title']} | {b['cluster']} | {m['A1']:.2f} | {m['A2']:.2f} | {m['A3']:.2f} | "
      f"{m['B']:.2f} | {d2b:+.1f}% | {d3b:+.1f}% |")
w(f"| **Corpus (all 150 responses)** | | **{rate([r for r in rows if r['cond']=='A1']):.2f}** | "
  f"**{rate([r for r in rows if r['cond']=='A2']):.2f}** | "
  f"**{rate([r for r in rows if r['cond']=='A3']):.2f}** | "
  f"**{rate([r for r in rows if r['cond']=='B']):.2f}** | "
  f"**{(rate([r for r in rows if r['cond']=='B'])-rate([r for r in rows if r['cond']=='A2']))/rate([r for r in rows if r['cond']=='A2'])*100:+.1f}%** | "
  f"**{(rate([r for r in rows if r['cond']=='B'])-rate([r for r in rows if r['cond']=='A3']))/rate([r for r in rows if r['cond']=='A3'])*100:+.1f}%** |")
w("")
w(f"- Books reduced A2→B: **{sum(x['d_a2b']<0 for x in perbook)}/10**. "
  f"Books reduced A3→B: **{sum(x['d_a3b']<0 for x in perbook)}/10**.")
w("- The corpus row is the mean over all 150 responses, which is not the mean "
  "of the ten book means (clusters are unequal in size).\n")
with open(os.path.join(HERE,"s7_per_book.csv"),"w",newline="",encoding="utf-8") as f:
    wr = csv.DictWriter(f, fieldnames=["ab","title","cluster","A1","A2","A3","B","d_a2b","d_a3b"])
    wr.writeheader(); wr.writerows(perbook)

# ------------------------------------------------------------------ S7.2
w("## S7.2 — Per-cluster D1–D3 rate by condition (per 1,000 tokens)\n")
w("| Cluster | Description | n books | A1 | A2 | A3 | B | Δ A2→B | Δ A3→B |")
w("|---|---|---|---|---|---|---|---|---|")
for k,v in CLUSTERS.items():
    abs_ = [ab for ab,b in BOOKS.items() if b["cluster"] == k]
    m = {c: rate([r for r in rows if r["ab"] in abs_ and r["cond"] == c]) for c in CONDS}
    w(f"| {k} | {v} | {len(abs_)} | {m['A1']:.2f} | {m['A2']:.2f} | {m['A3']:.2f} | "
      f"{m['B']:.2f} | {(m['B']-m['A2'])/m['A2']*100:+.1f}% | "
      f"{(m['B']-m['A3'])/m['A3']*100:+.1f}% |")
w("")
w("Clusters differ in baseline drift but the A2→B direction is identical in all "
  "three. With 2–4 books per cluster these are descriptive patterns, not "
  "statistical claims.\n")

# ------------------------------------------------------------------ S7.3
w("## S7.3 — All pairwise comparisons (paired Wilcoxon signed-rank, n = 150)\n")
w("Pairing is by (book, question). `p₁` is the one-sided alternative "
  "*a > b* — the convention used in the earlier papers for directional "
  "governance contrasts; `p₂` is two-sided. `r = Z/√150`, with Z recovered "
  "from `p₂`, matching the published effect sizes. Conclusions in the "
  "manuscript are stated on `p₂` unless noted.\n")
pw = []
for basis, field in (("D1–D3 (B stripped)","d123_per1k"),
                     ("D1–D3 (B raw)","d123_per1k_raw"),
                     ("Tier-1 (B stripped)","total_per1k"),
                     ("Tier-1 (B raw)","total_per1k_raw")):
    w(f"\n**{basis}**\n")
    w("| Contrast | mean (a) | mean (b) | Δ | W | p₁ (one-sided) | p₂ (two-sided) | r | n≠0 |")
    w("|---|---|---|---|---|---|---|---|---|")
    for a,b in itertools.combinations(CONDS,2):
        s = wtest(a,b,field); pw.append(dict(basis=basis, contrast=f"{a} vs {b}", **s))
        w(f"| {a} → {b} | {s['mean_a']:.3f} | {s['mean_b']:.3f} | {s['pct']:+.1f}% | "
          f"{s['W']:.1f} | {s['p1']:.2e} | {s['p2']:.2e} | {s['r']:.3f} | {s['n_nonzero']} |")
w("")
w("Note on W: scipy reports the signed-rank sum for the tested direction, so W "
  "here is the complement of the value in the earlier papers "
  "(W + W′ = n(n+1)/2 over non-zero pairs). The test and p-value are identical.\n")
with open(os.path.join(HERE,"s7_pairwise.csv"),"w",newline="",encoding="utf-8") as f:
    wr = csv.DictWriter(f, fieldnames=["basis","contrast","mean_a","mean_b","pct","W","p1","p2","r","n","n_nonzero"])
    wr.writeheader(); wr.writerows(pw)

# ------------------------------------------------------------------ S7.4
w("## S7.4 — Book-level clustered robustness check (n = 10)\n")
w("The 150 response pairs are not independent: 15 share each book. Collapsing "
  "to one mean per book per condition removes within-book dependence entirely "
  "and re-tests on n = 10. Exact Wilcoxon; the smallest attainable two-sided "
  "p at n = 10 is 1.95 × 10⁻³.\n")
w("| Contrast | Basis | mean (a) | mean (b) | Δ | W | p₁ | p₂ | books reducing |")
w("|---|---|---|---|---|---|---|---|---|")
for basis, field in (("D1–D3 (B stripped)","d123_per1k"), ("D1–D3 (B raw)","d123_per1k_raw")):
    for a,bb in itertools.combinations(CONDS,2):
        xs, ys = [], []
        for ab in sorted(BOOKS):
            raw = field.endswith("_raw")
            xs.append(rate([r for r in rows if r["ab"]==ab and r["cond"]==a],  raw=raw))
            ys.append(rate([r for r in rows if r["ab"]==ab and r["cond"]==bb], raw=raw))
        d = [x-y for x,y in zip(xs,ys)]
        if any(v != 0 for v in d):
            W,p1 = wilcoxon(xs,ys,alternative="greater",zero_method="wilcox")
            _,p2 = wilcoxon(xs,ys,alternative="two-sided",zero_method="wilcox")
        else: W,p1,p2 = float("nan"),1.0,1.0
        w(f"| {a} → {bb} | {basis} | {st.mean(xs):.3f} | {st.mean(ys):.3f} | "
          f"{(st.mean(ys)-st.mean(xs))/st.mean(xs)*100:+.1f}% | {W:.1f} | "
          f"{p1:.2e} | {p2:.2e} | {sum(v>0 for v in d)}/10 |")
w("")
w("The two significant deployment contrasts (A1→A2 model effect, A2→A3 prompt "
  "effect, A2→B combined) retain the minimum attainable p and 10/10 book-level "
  "consistency. The A3→B contrast remains null at book level, consistent with "
  "the response-level result.\n")


# ------------------------------------------------------------------ S7.5
w("## S7.5 — Effect-size convention: reconciliation with the earlier papers\n")
w("The script that produced the published figures (`drift_reduction_3way.py`) "
  "derives *r* from the p-value rather than from the rank sum, and clips the "
  "p-value before the conversion:\n")
w("```python")
w("p_for_z = p if alternative == \"two-sided\" else min(p * 2, 1.0)")
w("p_for_z = max(min(p_for_z, 0.999999), 1e-9)   # <- clip")
w("z = norm.ppf(1 - p_for_z / 2); r = z / (n ** 0.5)")
w("```")
w("")
w("Two consequences, both of which affect published numbers:\n")
w("1. **Upper cap.** The 1e-9 floor on p caps z at 6.109, so no reported *r* "
  "can exceed 6.109/√150 = **0.499**. Any contrast with a true p below 1e-9 is "
  "reported at the cap, understating its effect size.")
w("2. **Zeroing of counter-hypothesis effects.** For a one-sided test with "
  "p > 0.5 the doubling gives p_for_z = 1.0, which clips to 0.999999 and yields "
  "*r* ≈ 0.000. A published `r = 0.000` therefore means *the effect ran opposite "
  "to the one-sided hypothesis*, not *there was no effect*. In the A1-vs-B D4 "
  "comparison (A1 = 0.164, B = 0.655 per 1,000 tokens) the true effect is "
  "large and runs against governance; it was published as r = 0.000.\n")
w("This supplement recomputes *r* from the two-sided p with no clipping. "
  "Values therefore differ from the earlier papers where the cap or the floor "
  "was active. The underlying tests, W statistics and p-values are unchanged.\n")
w("| Contrast (Tier-1, B stripped) | mean (a) | mean (b) | Published *r* | Recomputed *r* | Cause of difference |")
w("|---|---|---|---|---|---|")
_rec = [("A2 vs B", 0.496, "none — reproduces exactly"),
        ("A1 vs A2", 0.499, "upper cap active (true p ≈ 2.6e-13 < 1e-9)"),
        ("A1 vs B", 0.000, "effect opposite to one-sided hypothesis → floored")]
for contrast, pubr, cause in _rec:
    s_ = [x for x in pw if x["basis"] == "Tier-1 (B stripped)" and x["contrast"] == contrast][0]
    w(f"| {contrast} | {s_['mean_a']:.3f} | {s_['mean_b']:.3f} | {pubr:.3f} | "
      f"{s_['r']:.3f} | {cause} |")
w("")
w("No headline conclusion changes: the A2→B deployment contrast — the paper's "
  "main claim — reproduces the published effect size exactly. The corrections "
  "make the model effect (A1→A2) *larger* than published and make the adverse "
  "D4 interface effect visible rather than zeroed.\n")

open(os.path.join(HERE,"supplement_tables.md"),"w",encoding="utf-8").write("\n".join(out))
print("WROTE supplement_tables.md\n")
print("\n".join(out[:2]))
